# Generated by Django 4.2.5 on 2023-10-06 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_subject_name_alter_vocabularyword_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vocabularyword',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subject'),
        ),
    ]
