# Generated by Django 4.2.7 on 2023-11-12 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_groupname_group_name_alter_groupname_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupname',
            name='group_name',
            field=models.CharField(blank=True, default='others', max_length=255, null=True),
        ),
    ]
