# Generated by Django 4.2.7 on 2023-11-23 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_vocabularyword_group_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupname',
            name='group_name',
            field=models.CharField(default='others', max_length=255),
        ),
    ]
